name: cae_precursor_env
channels:
  - defaults
dependencies:
  - python=3.9
  - tensorflow==2.10
  - ipykernel
  - h5py=3.8.0
  - matplotlib=3.7.1
  - pip:
      - einops==0.8.0
      - filelock==3.17.0
      - fsspec==2024.12.0
      - jinja2==3.1.5
      - kolsol==1.0.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - sympy==1.13.1
      - torch==2.5.1
      - tqdm==4.67.1